import { useEffect, useMemo, useRef, useState } from 'react'
import { motion } from 'framer-motion'
import { useNavigate } from 'react-router-dom'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { useAuth } from '../context/AuthContext'
import {
  AlertTriangle,
  Brain,
  CheckCircle,
  ChevronLeft,
  ChevronRight,
  DollarSign,
  Info,
  Lock,
  Mic,
  Sparkles,
  Shield
} from 'lucide-react'
import {
  buildAiFeedback,
  calculateFounderScore,
  compareAgainstPeers,
  computeDropoffState,
  evaluateExecutionStep,
  evaluateIdentityStep,
  evaluateReadinessStep,
  initialVerificationForm,
  loadInvestorRecords,
  saveInvestorRecord,
  toInvestorRecord
} from '../lib/founderVerification'

const identityFieldConfig = {
  founderName: {
    label: 'Founder Legal Name',
    placeholder: 'Aarav Mehta',
    helper: 'Must match your government ID to pass verification.',
    trustCue: 'Used only for identity checks. Encrypted at rest.'
  },
  officialEmail: {
    label: 'Official Email',
    placeholder: 'founder@company.com',
    helper: 'A company or professional email boosts credibility with investors.',
    trustCue: 'We never expose your email publicly without consent.'
  },
  city: {
    label: 'City',
    placeholder: 'Bengaluru',
    helper: 'Helps us benchmark your profile against relevant local startup ecosystems.',
    trustCue: 'Only city-level data is used for matching and analytics.'
  },
  governmentIdUrl: {
    label: 'Government ID Upload',
    placeholder: 'Upload from camera or gallery',
    helper: 'Click a clear photo or upload a valid government-issued ID image.',
    trustCue: 'Files are encrypted and access-restricted for verification only.'
  },
  governmentIdNumber: {
    label: 'Government ID Number',
    placeholder: 'ABCD1234E',
    helper: 'Used to verify document consistency and reduce impersonation risk.',
    trustCue: 'Stored securely and masked in operational views.'
  },
  selfieUrl: {
    label: 'Selfie Upload',
    placeholder: 'Capture a live selfie or upload from gallery',
    helper: 'Click a recent, clear selfie or upload one from your gallery.',
    trustCue: 'Biometric checks are encrypted and never sold or shared.'
  },
  faceMatchScore: {
    label: 'Face Match Score (Auto-generated)',
    placeholder: 'Auto-generated after both uploads',
    helper: 'Calculated automatically from ID and selfie similarity.',
    trustCue: 'Score is generated by verification logic, not manual review bias.'
  },
  linkedinUrl: {
    label: 'LinkedIn Profile URL',
    placeholder: 'https://www.linkedin.com/in/aaravmehta',
    helper: 'A complete and active LinkedIn profile strengthens trust.',
    trustCue: 'We only read publicly available profile metadata.'
  },
  linkedinHeadline: {
    label: 'LinkedIn Headline & Experience Summary',
    placeholder: 'Founder at FoundrHUB | Ex-PM at Acme | 8+ years in SaaS',
    helper: 'Share concise experience highlights to support your founder story.',
    trustCue: 'Used only for credibility assessment in this verification flow.'
  }
}

const stepMeta = [
  {
    key: 'identity',
    title: 'Identity & Credibility',
    subtitle: 'ID + selfie + LinkedIn signal extraction',
    output: 'Authenticity Score'
  },
  {
    key: 'execution',
    title: 'Execution Proof',
    subtitle: 'Working product, quality proof, clarity checks',
    output: 'Execution Score'
  },
  {
    key: 'readiness',
    title: 'Traction & Investor Readiness',
    subtitle: 'Metrics, deck quality, market clarity',
    output: 'Investor Readiness Score'
  }
]

const userRangeOptions = [
  { label: '0-100', value: 100 },
  { label: '100-1K', value: 1000 },
  { label: '1K-10K', value: 10000 },
  { label: '10K+', value: 50000 }
]

const askSuggestions = [25000, 50000, 100000, 250000, 500000]

const StepTag = ({ index, active, complete }) => (
  <div className={`w-10 h-10 rounded-2xl flex items-center justify-center text-sm font-black border transition-all ${complete ? 'bg-emerald-500 text-white border-emerald-500' : active ? 'bg-[#122056] text-white border-[#122056]' : 'bg-white text-[#122056]/50 border-[#E6EAFD]'}`}>
    {complete ? <CheckCircle size={16} /> : `0${index + 1}`}
  </div>
)

const VerifyPage = () => {
  const { updateUser } = useAuth()
  const navigate = useNavigate()
  const [step, setStep] = useState(0)
  const [form, setForm] = useState(initialVerificationForm)
  const [submitted, setSubmitted] = useState(false)
  const [identityResult, setIdentityResult] = useState(null)
  const [executionResult, setExecutionResult] = useState(null)
  const [readinessResult, setReadinessResult] = useState(null)
  const [finalReport, setFinalReport] = useState(null)
  const [aiFeedback, setAiFeedback] = useState(null)
  const [dropoffState, setDropoffState] = useState({ risk: 'low', idleMinutes: 0, totalMinutes: 0, activeStep: 0 })
  const [sessionMeta, setSessionMeta] = useState({ startedAt: Date.now(), lastUpdatedAt: Date.now() })
  const [investorRecords, setInvestorRecords] = useState([])
  const [identityTouched, setIdentityTouched] = useState({})
  const [linkedInStatus, setLinkedInStatus] = useState({ state: 'idle', message: '' })
  const [identityUploads, setIdentityUploads] = useState({ governmentIdName: '', selfieName: '' })
  const [readinessTouched, setReadinessTouched] = useState({})
  const [revenueMode, setRevenueMode] = useState('pre-revenue')
  const [deckUpload, setDeckUpload] = useState({ status: 'idle', fileName: '' })
  const [isDeckDragOver, setIsDeckDragOver] = useState(false)
  const [voiceStatus, setVoiceStatus] = useState('idle')
  const [voiceNote, setVoiceNote] = useState('')
  const idCameraRef = useRef(null)
  const idGalleryRef = useRef(null)
  const selfieCameraRef = useRef(null)
  const selfieGalleryRef = useRef(null)
  const deckUploadRef = useRef(null)

  const isEmailValid = (value) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(value || '').trim())
  const isUrlValid = (value) => /^(https?:\/\/|data:image\/|blob:)/i.test(String(value || '').trim())
  const isNameLikelyFake = (value) => /(test|asdf|qwerty|admin|fake|unknown)/i.test(String(value || '').trim())
  const isRandomEmail = (value) => /@(mailinator|tempmail|10minutemail|yopmail)\./i.test(String(value || '').trim())

  const getIdentityFieldError = (key, value) => {
    if (key === 'founderName') {
      if (!String(value || '').trim()) return 'Please enter your legal name as shown on your ID.'
      if (String(value || '').trim().length < 3) return 'This looks too short. Please enter your full legal name.'
      if (isNameLikelyFake(value)) return 'This name looks unusual. Use your legal name for verification.'
    }

    if (key === 'officialEmail') {
      if (!String(value || '').trim()) return 'Add your official email so we can verify contact authenticity.'
      if (!isEmailValid(value)) return 'That email format seems off. Try name@company.com.'
      if (isRandomEmail(value)) return 'Disposable emails are not accepted for founder verification.'
    }

    if (key === 'city') {
      if (!String(value || '').trim()) return 'Tell us your city so we can map your ecosystem context.'
      if (String(value || '').trim().length < 2) return 'Please enter a valid city name.'
    }

    if (key === 'governmentIdUrl') {
      if (!String(value || '').trim()) return 'Please upload your government ID image from camera or gallery.'
      if (!isUrlValid(value)) return 'Could not read this file. Please upload a clear image again.'
    }

    if (key === 'governmentIdNumber') {
      if (!String(value || '').trim()) return 'Enter your government ID number.'
      if (String(value || '').trim().length < 6) return 'This ID number looks too short. Please re-check it.'
    }

    if (key === 'selfieUrl') {
      if (!String(value || '').trim()) return 'Please capture or upload a live selfie to continue.'
      if (!isUrlValid(value)) return 'Could not read this selfie image. Please upload again.'
    }

    if (key === 'linkedinUrl') {
      if (!String(value || '').trim()) return 'Add your LinkedIn profile link to complete credibility checks.'
      if (!/^https?:\/\/(www\.)?linkedin\.com\//i.test(String(value || '').trim())) {
        return 'Use a valid LinkedIn URL, such as https://www.linkedin.com/in/yourname.'
      }
    }

    if (key === 'linkedinHeadline') {
      if (!String(value || '').trim()) return 'Share a short headline and experience summary.'
      if (String(value || '').trim().length < 20) return 'Add a bit more detail so reviewers can trust your background.'
    }

    return ''
  }

  const handleIdentityImageUpload = (event, fieldKey, nameKey) => {
    const file = event.target.files?.[0]
    if (!file) return

    if (!file.type.startsWith('image/')) {
      setIdentityTouched((prev) => ({ ...prev, [fieldKey]: true }))
      event.target.value = ''
      return
    }

    const reader = new FileReader()
    reader.onload = () => {
      up(fieldKey, String(reader.result || ''))
      setIdentityUploads((prev) => ({ ...prev, [nameKey]: file.name }))
    }
    reader.readAsDataURL(file)
    event.target.value = ''
  }

  const up = (k, v) => {
    setForm((prev) => ({ ...prev, [k]: v }))
    setSessionMeta((prev) => ({ ...prev, lastUpdatedAt: Date.now() }))
    setIdentityTouched((prev) => ({ ...prev, [k]: true }))
    setReadinessTouched((prev) => ({ ...prev, [k]: true }))
  }

  const markReadinessTouched = (fields) => {
    setReadinessTouched((prev) => {
      const next = { ...prev }
      fields.forEach((f) => {
        next[f] = true
      })
      return next
    })
  }

  const readinessLive = useMemo(() => evaluateReadinessStep(form), [form])

  const readinessSections = useMemo(() => {
    const tractionComplete = Boolean(form.totalUsers) && Boolean(form.monthlyActiveUsers) && Number(form.growthRateMonthly || 0) > 0
    const businessComplete = Boolean(form.businessModel?.trim()) && Boolean(form.askAmountUsd) && Boolean(form.pitchDeckUrl)
    const marketComplete = Boolean(form.targetMarket?.trim()) && Boolean(form.competitors?.trim())

    return [
      {
        key: 'traction',
        title: 'Traction Signals',
        complete: tractionComplete,
        contribution: Math.round((readinessLive.details?.tractionScore || 0) * 50)
      },
      {
        key: 'business',
        title: 'Business Model',
        complete: businessComplete,
        contribution: Math.round((readinessLive.details?.narrativeScore || 0) * 35)
      },
      {
        key: 'market',
        title: 'Market Understanding',
        complete: marketComplete,
        contribution: (readinessLive.details?.deckSignal || 0) ? 15 : 0
      }
    ]
  }, [form, readinessLive])

  const readinessCriticalErrors = useMemo(() => {
    const issues = []

    if (!form.totalUsers) issues.push('Add a traction range or manual total users input.')
    if (!form.growthRateMonthly) issues.push('Set monthly growth to show momentum.')
    if (!form.askAmountUsd) issues.push('Add your funding ask to complete readiness analysis.')
    if (!form.pitchDeckUrl) issues.push('Upload your pitch deck to unlock investor readiness.')
    if (!form.businessModel?.trim()) issues.push('Describe your business model in at least a few lines.')
    if (!form.targetMarket?.trim()) issues.push('Define your target market clearly.')
    if (!form.competitors?.trim()) issues.push('List competitors and differentiation.')

    if (Number(form.totalUsers || 0) > 10000 && Number(form.monthlyActiveUsers || 0) < 50) {
      issues.push('User count and MAU seem inconsistent. Please verify traction accuracy.')
    }
    if (Number(form.growthRateMonthly || 0) > 60 && revenueMode === 'pre-revenue' && Number(form.totalUsers || 0) < 100) {
      issues.push('Very high growth with low users looks unrealistic. Recheck metrics.')
    }
    if ((form.competitors || '').trim().toLowerCase() === 'none') {
      issues.push('No competitors is usually unrealistic. Mention alternatives and your edge.')
    }

    return issues
  }, [form, revenueMode])

  const readinessAiFeedback = useMemo(() => {
    const positives = []
    const warnings = []
    const redFlags = []

    if (Number(form.growthRateMonthly || 0) >= 15) positives.push('Strong early traction momentum.')
    if (Number(form.totalUsers || 0) >= 1000) positives.push('Healthy top-of-funnel adoption signal.')
    if (revenueMode === 'revenue' && Number(form.monthlyRevenue || 0) > 0) positives.push('Revenue signal improves investor confidence.')

    if (revenueMode === 'pre-revenue' && Number(form.growthRateMonthly || 0) < 10) warnings.push('No revenue yet. Pair this with stronger growth proof.')
    if ((form.businessModel || '').trim().length < 45) warnings.push('Business model is unclear. Add pricing and monetization mechanics.')

    if ((form.competitors || '').trim().toLowerCase() === 'none') redFlags.push('No competitors is unrealistic.')
    if (Number(form.totalUsers || 0) > 50000 && Number(form.monthlyRevenue || 0) === 0 && revenueMode === 'revenue') {
      redFlags.push('Large user base with no revenue data looks inconsistent.')
    }

    return { positives, warnings, redFlags }
  }, [form, revenueMode])

  const readinessBadges = useMemo(() => {
    const builder = Boolean(form.mvpLink || form.demoLink || form.githubUrl || form.websiteUrl)
    const growingStartup = Number(form.totalUsers || 0) > 0 && Number(form.growthRateMonthly || 0) >= 8
    const investorReady = readinessCriticalErrors.length === 0 && readinessLive.score >= 65
    return { builder, growingStartup, investorReady }
  }, [form, readinessCriticalErrors, readinessLive])

  const readinessNextAction = useMemo(() => {
    if (!form.pitchDeckUrl) return 'Upload a strong pitch deck to unlock investor readiness confidence.'
    if ((form.businessModel || '').trim().length < 45) return 'Clarify pricing, margins, and monetization in your business model.'
    if (revenueMode === 'pre-revenue' && Number(form.growthRateMonthly || 0) < 10) return 'Strengthen traction narrative with user retention or growth proof.'
    if ((form.competitors || '').trim().toLowerCase() === 'none') return 'Add realistic competitors and your moat.'
    return 'Your profile looks strong. Finalize and submit for verification.'
  }, [form, revenueMode])

  const executionLive = useMemo(() => evaluateExecutionStep(form), [form])

  const executionStageOptions = useMemo(() => ([
    { label: 'Idea', value: 'idea' },
    { label: 'Wireframe', value: 'wireframe' },
    { label: 'Prototype', value: 'prototype' },
    { label: 'MVP', value: 'mvp' },
    { label: 'Live', value: 'live' }
  ]), [])

  const executionSections = useMemo(() => {
    const productComplete = [form.mvpLink, form.demoLink, form.githubUrl, form.websiteUrl].filter((value) => isUrlValid(value)).length >= 2
    const narrativeComplete = (form.problemStatement || '').trim().length >= 40 && (form.solutionDescription || '').trim().length >= 60
    const screenshotComplete = (form.screenshotLinks || '').split(',').map((v) => v.trim()).filter(Boolean).length >= 2

    return [
      {
        key: 'product',
        title: 'Product Proof',
        complete: productComplete,
        contribution: Math.round((executionLive.details?.buildEvidence || 0) * 45)
      },
      {
        key: 'narrative',
        title: 'Problem-Solution Clarity',
        complete: narrativeComplete,
        contribution: Math.round((executionLive.details?.clarity || 0) * 30)
      },
      {
        key: 'stage',
        title: 'Build Stage & Evidence',
        complete: screenshotComplete,
        contribution: Math.round((executionLive.details?.stageWeight || 0) * 25)
      }
    ]
  }, [form, executionLive, isUrlValid])

  const executionCriticalErrors = useMemo(() => {
    const issues = []

    if ([form.mvpLink, form.demoLink, form.githubUrl, form.websiteUrl].filter((value) => isUrlValid(value)).length < 2) {
      issues.push('Add at least 2 valid links among MVP, demo, GitHub, or website.')
    }
    if ((form.problemStatement || '').trim().length < 40) {
      issues.push('Expand your problem statement with concrete pain points.')
    }
    if ((form.solutionDescription || '').trim().length < 60) {
      issues.push('Add more detail in solution description with workflow clarity.')
    }
    if ((form.screenshotLinks || '').split(',').map((v) => v.trim()).filter(Boolean).length === 0) {
      issues.push('Attach at least one product screenshot URL.')
    }
    if (form.prototypeStage === 'idea' && [form.mvpLink, form.demoLink, form.githubUrl, form.websiteUrl].filter((value) => isUrlValid(value)).length > 0) {
      issues.push('Prototype stage says idea, but links suggest build exists. Reconcile this signal.')
    }

    return issues
  }, [form, isUrlValid])

  const executionNextAction = useMemo(() => {
    if ([form.mvpLink, form.demoLink, form.githubUrl, form.websiteUrl].filter((value) => isUrlValid(value)).length < 2) {
      return 'Add one more proof link to strengthen execution confidence.'
    }
    if ((form.solutionDescription || '').trim().length < 60) {
      return 'Deepen your solution flow: onboarding, core loop, and differentiator.'
    }
    if ((form.screenshotLinks || '').split(',').map((v) => v.trim()).filter(Boolean).length < 2) {
      return 'Add screenshot links showing onboarding, dashboard, and a key user outcome.'
    }
    return 'Execution proof looks solid. Move to traction and investor readiness.'
  }, [form, isUrlValid])

  const executionProgress = useMemo(() => {
    const completeCount = executionSections.filter((section) => section.complete).length
    return Math.round((completeCount / executionSections.length) * 100)
  }, [executionSections])

  const coreIdentityReady = useMemo(() => {
    return (
      !getIdentityFieldError('founderName', form.founderName) &&
      !getIdentityFieldError('officialEmail', form.officialEmail) &&
      !getIdentityFieldError('city', form.city)
    )
  }, [form])

  const idVerificationReady = useMemo(() => {
    return (
      !getIdentityFieldError('governmentIdUrl', form.governmentIdUrl) &&
      !getIdentityFieldError('governmentIdNumber', form.governmentIdNumber) &&
      !getIdentityFieldError('selfieUrl', form.selfieUrl) &&
      Number(form.faceMatchScore || 0) >= 60
    )
  }, [form])

  const authenticityPreview = useMemo(() => {
    return evaluateIdentityStep(form).score
  }, [form])

  const step1RequiredFields = useMemo(() => ([
    'founderName',
    'officialEmail',
    'city',
    'governmentIdUrl',
    'governmentIdNumber',
    'selfieUrl',
    'linkedinUrl',
    'linkedinHeadline'
  ]), [])

  const step1ErrorList = useMemo(() => {
    const errors = step1RequiredFields
      .map((key) => getIdentityFieldError(key, form[key]))
      .filter(Boolean)

    if (Number(form.faceMatchScore || 0) > 0 && Number(form.faceMatchScore || 0) < 60) {
      errors.push('Face match confidence is low. Upload clearer ID and selfie images.')
    }

    return [...new Set(errors)]
  }, [form, step1RequiredFields])

  const step1CompletionPercent = useMemo(() => {
    const validCount = step1RequiredFields.filter((key) => !getIdentityFieldError(key, form[key])).length
    return Math.round((validCount / step1RequiredFields.length) * 100)
  }, [form, step1RequiredFields])

  const completionRatio = useMemo(() => {
    const filled = Object.values(form).filter((value) => {
      if (typeof value === 'boolean') return value
      if (typeof value === 'number') return value > 0
      return String(value || '').trim().length > 0
    }).length
    return Math.round((filled / Object.keys(form).length) * 100)
  }, [form])

  useEffect(() => {
    setInvestorRecords(loadInvestorRecords())
  }, [])

  useEffect(() => {
    const interval = setInterval(() => {
      setDropoffState(
        computeDropoffState({
          startedAt: sessionMeta.startedAt,
          lastUpdatedAt: sessionMeta.lastUpdatedAt,
          activeStep: step,
          completedStepCount: [identityResult, executionResult, readinessResult].filter(Boolean).length
        })
      )
    }, 20000)

    return () => clearInterval(interval)
  }, [sessionMeta, step, identityResult, executionResult, readinessResult])

  useEffect(() => {
    const onBeforeUnload = () => {
      if (submitted) return
      const dropoffEvent = {
        at: new Date().toISOString(),
        step,
        risk: dropoffState.risk,
        completionRatio
      }
      const key = 'fh_dropoff_events'
      const existing = JSON.parse(window.localStorage.getItem(key) || '[]')
      window.localStorage.setItem(key, JSON.stringify([dropoffEvent, ...existing].slice(0, 20)))
    }

    window.addEventListener('beforeunload', onBeforeUnload)
    return () => window.removeEventListener('beforeunload', onBeforeUnload)
  }, [submitted, step, dropoffState, completionRatio])

  useEffect(() => {
    if (!form.governmentIdUrl || !form.selfieUrl) {
      if (form.faceMatchScore !== 0) {
        setForm((prev) => ({ ...prev, faceMatchScore: 0 }))
      }
      return
    }

    const idLength = String(form.governmentIdUrl).trim().length
    const selfieLength = String(form.selfieUrl).trim().length
    const baseScore = Math.min(95, 55 + ((idLength + selfieLength) % 35))

    if (Number(form.faceMatchScore) !== baseScore) {
      setForm((prev) => ({ ...prev, faceMatchScore: baseScore }))
    }
  }, [form.governmentIdUrl, form.selfieUrl, form.faceMatchScore])

  useEffect(() => {
    if (!form.linkedinUrl) {
      setLinkedInStatus({ state: 'idle', message: '' })
      return
    }

    const linkedinRegex = /^https?:\/\/(www\.)?linkedin\.com\/(in|company)\/[a-zA-Z0-9-_%]+\/?$/i
    if (!linkedinRegex.test(String(form.linkedinUrl).trim())) {
      setLinkedInStatus({ state: 'invalid', message: 'LinkedIn URL format looks incomplete.' })
      return
    }

    setLinkedInStatus({ state: 'checking', message: 'Checking profile signal...' })
    const timer = setTimeout(() => {
      setLinkedInStatus({ state: 'valid', message: 'Profile signal looks active.' })
    }, 500)

    return () => clearTimeout(timer)
  }, [form.linkedinUrl])

  useEffect(() => {
    const verified = isEmailValid(form.officialEmail) && !isRandomEmail(form.officialEmail)
    if (form.emailVerified !== verified) {
      setForm((prev) => ({ ...prev, emailVerified: verified }))
    }
  }, [form.officialEmail, form.emailVerified])

  useEffect(() => {
    if (revenueMode === 'pre-revenue' && String(form.monthlyRevenue || '').trim() !== '') {
      setForm((prev) => ({ ...prev, monthlyRevenue: '' }))
    }
  }, [revenueMode, form.monthlyRevenue])

  const handleDeckFile = (file) => {
    if (!file) return
    const valid = /(pdf|ppt|pptx|key|odp)$/i.test(file.name)
    if (!valid) {
      setDeckUpload({ status: 'error', fileName: 'Unsupported file type' })
      return
    }

    const objectUrl = URL.createObjectURL(file)
    up('pitchDeckUrl', objectUrl)
    setDeckUpload({ status: 'uploaded', fileName: file.name })
  }

  const startVoiceCapture = () => {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SpeechRecognition) {
      setVoiceStatus('unsupported')
      return
    }

    const recognition = new SpeechRecognition()
    recognition.lang = 'en-US'
    recognition.interimResults = false
    recognition.maxAlternatives = 1

    setVoiceStatus('listening')
    recognition.onresult = (event) => {
      const transcript = event.results?.[0]?.[0]?.transcript || ''
      setVoiceNote(transcript)
      up('businessModel', `${form.businessModel ? `${form.businessModel} ` : ''}${transcript}`.trim())
      setVoiceStatus('captured')
    }
    recognition.onerror = () => setVoiceStatus('error')
    recognition.onend = () => {
      if (voiceStatus === 'listening') setVoiceStatus('idle')
    }

    recognition.start()
  }

  const evaluateCurrentStep = () => {
    if (step === 0) {
      const result = evaluateIdentityStep(form)
      setIdentityResult(result)
      return result
    }
    if (step === 1) {
      const result = evaluateExecutionStep(form)
      setExecutionResult(result)
      return result
    }

    const result = evaluateReadinessStep(form)
    setReadinessResult(result)
    return result
  }

  const handleNext = () => {
    evaluateCurrentStep()
    if (step < 2) setStep((prev) => prev + 1)
  }

  const handleSubmit = () => {
    if (step === 2 && readinessCriticalErrors.length > 0) {
      markReadinessTouched(['totalUsers', 'growthRateMonthly', 'askAmountUsd', 'pitchDeckUrl', 'businessModel', 'targetMarket', 'competitors'])
      return
    }

    const identity = identityResult || evaluateIdentityStep(form)
    const execution = executionResult || evaluateExecutionStep(form)
    const readiness = readinessResult || evaluateReadinessStep(form)

    const composite = calculateFounderScore({
      authenticityScore: identity.score,
      executionScore: execution.score,
      investorReadinessScore: readiness.score
    })

    const mergedAi = buildAiFeedback({
      identityResult: identity,
      executionResult: execution,
      readinessResult: readiness
    })

    const allFlags = [...identity.flags, ...execution.flags, ...readiness.flags, ...composite.riskFlags]

    const record = toInvestorRecord({
      form,
      scores: {
        authenticityScore: identity.score,
        executionScore: execution.score,
        investorReadinessScore: readiness.score,
        founderScore: composite.finalScore
      },
      badges: composite.badges,
      flags: allFlags,
      dropoff: dropoffState
    })

    saveInvestorRecord(record)
    setInvestorRecords(loadInvestorRecords())

    const peerBenchmark = compareAgainstPeers({
      city: form.city,
      category: form.category,
      currentFounder: {
        id: record.id,
        startupName: record.startupName,
        city: record.city,
        category: record.category,
        founderScore: record.founderScore,
        executionScore: record.executionScore,
        investorReadinessScore: record.investorReadinessScore
      }
    })

    setFinalReport({
      ...composite,
      authenticityScore: identity.score,
      executionScore: execution.score,
      investorReadinessScore: readiness.score,
      allFlags,
      peerBenchmark,
      record
    })
    setAiFeedback(mergedAi)

    updateUser({
      brandName: form.startupName,
      category: form.category,
      city: form.city,
      website: form.websiteUrl,
      story: form.solutionDescription,
      verification: {
        isCompleted: true,
        completedAt: new Date().toISOString(),
        authenticityScore: identity.score,
        executionScore: execution.score,
        investorReadinessScore: readiness.score,
        founderScore: composite.finalScore,
        badges: composite.badges
      }
    })

    setSubmitted(true)
  }

  return (
    <>
      <Navbar />
      <main className="pt-[72px] min-h-screen bg-gradient-to-b from-[#FAFAFD] to-white">
        <section className="py-14 lg:py-16 relative overflow-hidden">
          <div className="absolute top-0 left-0 w-full h-full pointer-events-none">
            <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] bg-[#5B65DC]/5 rounded-full blur-[120px]" />
            <div className="absolute top-[20%] right-[-5%] w-[30%] h-[30%] bg-[#122056]/5 rounded-full blur-[100px]" />
          </div>

          <div className="max-w-7xl mx-auto px-6 lg:px-10 relative z-10">
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }} className="text-center max-w-3xl mx-auto mb-10">
              <span className="text-[10px] font-black tracking-[0.2em] uppercase text-[#5B65DC] mb-4 block">Founder Signal Engine</span>
              <h1 className="font-serif text-[clamp(2rem,4.2vw,3.2rem)] leading-[1.1] text-[#122056] mb-4">3-Step Founder Verification</h1>
              <p className="text-[15px] text-[#122056]/60 leading-relaxed font-medium">Complete these details once to verify your founder profile and unlock your dashboard.</p>
            </motion.div>

            <div className="max-w-6xl mx-auto mb-7 px-5 py-5 bg-white/70 backdrop-blur-2xl border border-[#EEF0FD] rounded-[2.2rem] shadow-2xl shadow-[#122056]/5">
              <div className="flex flex-wrap lg:flex-nowrap gap-4 lg:gap-0 items-center justify-between">
                {stepMeta.map((s, i) => (
                  <div key={s.key} className="flex items-center gap-3 flex-1 min-w-[220px]">
                    <StepTag index={i} active={i === step} complete={i < step || (submitted && i <= step)} />
                    <div>
                      <p className={`text-[11px] uppercase tracking-[0.13em] font-black ${i <= step ? 'text-[#122056]' : 'text-[#122056]/30'}`}>{s.title}</p>
                      <p className="text-xs text-[#122056]/45">{s.output}</p>
                    </div>
                    {i < stepMeta.length - 1 && <div className="hidden lg:block h-[1px] flex-1 bg-[#E2E8FC] rounded-full ml-3" />}
                  </div>
                ))}
              </div>
              <div className="mt-4 h-2 rounded-full bg-[#EEF0FD] overflow-hidden">
                <div className="h-full bg-gradient-to-r from-[#5B65DC] to-[#0EA5E9] transition-all" style={{ width: `${((step + (submitted ? 1 : 0)) / 3) * 100}%` }} />
              </div>
              <div className="mt-3 text-xs text-[#122056]/55">Completion: {completionRatio}%</div>
            </div>

            {!submitted ? (
              <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="max-w-4xl mx-auto">
                <div className="bg-white rounded-[2.2rem] border border-[#E9EEFF] p-7 lg:p-9 shadow-[0_20px_48px_-16px_rgba(18,32,86,0.12)]">
                  <div className="mb-7">
                    <p className="text-xs uppercase tracking-[0.16em] font-black text-[#5B65DC]">Step {step + 1} of 3</p>
                    <h2 className="text-2xl font-serif text-[#122056] mt-2">{stepMeta[step].title}</h2>
                    <p className="text-sm text-[#122056]/55 mt-1">{stepMeta[step].subtitle}</p>
                  </div>

                  {step === 0 && (
                    <div className="grid lg:grid-cols-[1fr_300px] gap-6 items-start">
                      <div className="space-y-6">
                        <div className="rounded-2xl border border-[#E9EEFF] bg-[#FBFCFF] p-4">
                          <p className="text-[11px] font-black uppercase tracking-[0.14em] text-[#5B65DC] mb-2">Trust & Privacy</p>
                          <p className="text-sm text-[#122056]/70 inline-flex items-center gap-2"><Lock size={14} /> Your identity data is encrypted and used only for verification.</p>
                        </div>

                        <div className="space-y-4">
                          <p className="text-[11px] uppercase tracking-[0.14em] font-black text-[#5B65DC]">A. Core Identity</p>
                          <div className="grid md:grid-cols-2 gap-4">
                          <div>
                            <label className="verify-label">{identityFieldConfig.founderName.label}</label>
                            <input value={form.founderName} onChange={(e) => up('founderName', e.target.value)} className={`verify-input ${identityTouched.founderName && getIdentityFieldError('founderName', form.founderName) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.founderName.placeholder} />
                            <p className="verify-helper">{identityFieldConfig.founderName.helper}</p>
                            <p className="verify-trust">{identityFieldConfig.founderName.trustCue}</p>
                            {identityTouched.founderName && getIdentityFieldError('founderName', form.founderName) && <p className="verify-error">{getIdentityFieldError('founderName', form.founderName)}</p>}
                          </div>

                          <div>
                            <label className="verify-label">{identityFieldConfig.officialEmail.label}</label>
                            <input type="email" value={form.officialEmail} onChange={(e) => up('officialEmail', e.target.value)} className={`verify-input ${identityTouched.officialEmail && getIdentityFieldError('officialEmail', form.officialEmail) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.officialEmail.placeholder} />
                            <p className="verify-helper">{identityFieldConfig.officialEmail.helper}</p>
                            <p className="verify-trust">{identityFieldConfig.officialEmail.trustCue}</p>
                            {form.emailVerified && <p className="verify-success">Email signal verified.</p>}
                            {identityTouched.officialEmail && getIdentityFieldError('officialEmail', form.officialEmail) && <p className="verify-error">{getIdentityFieldError('officialEmail', form.officialEmail)}</p>}
                          </div>

                          <div>
                            <label className="verify-label">{identityFieldConfig.city.label}</label>
                            <input value={form.city} onChange={(e) => up('city', e.target.value)} className={`verify-input ${identityTouched.city && getIdentityFieldError('city', form.city) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.city.placeholder} />
                            <p className="verify-helper">{identityFieldConfig.city.helper}</p>
                            <p className="verify-trust">{identityFieldConfig.city.trustCue}</p>
                            {identityTouched.city && getIdentityFieldError('city', form.city) && <p className="verify-error">{getIdentityFieldError('city', form.city)}</p>}
                          </div>
                          </div>
                        </div>

                        {coreIdentityReady && (
                          <div className="space-y-4">
                            <p className="text-[11px] uppercase tracking-[0.14em] font-black text-[#5B65DC]">B. Government ID & Liveness</p>
                            <div className="grid md:grid-cols-2 gap-4">
                            <div>
                              <label className="verify-label">{identityFieldConfig.governmentIdUrl.label}</label>
                              <div className={`verify-upload-box ${identityTouched.governmentIdUrl && getIdentityFieldError('governmentIdUrl', form.governmentIdUrl) ? 'verify-input-error' : ''}`}>
                                <div className="flex flex-wrap gap-2">
                                  <button type="button" className="verify-upload-btn" onClick={() => idCameraRef.current?.click()}>Use Camera</button>
                                  <button type="button" className="verify-upload-btn" onClick={() => idGalleryRef.current?.click()}>Upload from Gallery</button>
                                </div>
                                <input
                                  ref={idCameraRef}
                                  type="file"
                                  accept="image/*"
                                  capture="environment"
                                  className="hidden"
                                  onChange={(e) => handleIdentityImageUpload(e, 'governmentIdUrl', 'governmentIdName')}
                                />
                                <input
                                  ref={idGalleryRef}
                                  type="file"
                                  accept="image/*"
                                  className="hidden"
                                  onChange={(e) => handleIdentityImageUpload(e, 'governmentIdUrl', 'governmentIdName')}
                                />
                                <p className="verify-upload-name">{identityUploads.governmentIdName || identityFieldConfig.governmentIdUrl.placeholder}</p>
                                {form.governmentIdUrl && <img src={form.governmentIdUrl} alt="Government ID preview" className="verify-preview" />}
                              </div>
                              <p className="verify-helper">{identityFieldConfig.governmentIdUrl.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.governmentIdUrl.trustCue}</p>
                              {identityTouched.governmentIdUrl && getIdentityFieldError('governmentIdUrl', form.governmentIdUrl) && <p className="verify-error">{getIdentityFieldError('governmentIdUrl', form.governmentIdUrl)}</p>}
                            </div>

                            <div>
                              <label className="verify-label">{identityFieldConfig.governmentIdNumber.label}</label>
                              <input value={form.governmentIdNumber} onChange={(e) => up('governmentIdNumber', e.target.value)} className={`verify-input ${identityTouched.governmentIdNumber && getIdentityFieldError('governmentIdNumber', form.governmentIdNumber) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.governmentIdNumber.placeholder} />
                              <p className="verify-helper">{identityFieldConfig.governmentIdNumber.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.governmentIdNumber.trustCue}</p>
                              {identityTouched.governmentIdNumber && getIdentityFieldError('governmentIdNumber', form.governmentIdNumber) && <p className="verify-error">{getIdentityFieldError('governmentIdNumber', form.governmentIdNumber)}</p>}
                            </div>

                            <div>
                              <label className="verify-label">{identityFieldConfig.selfieUrl.label}</label>
                              <div className={`verify-upload-box ${identityTouched.selfieUrl && getIdentityFieldError('selfieUrl', form.selfieUrl) ? 'verify-input-error' : ''}`}>
                                <div className="flex flex-wrap gap-2">
                                  <button type="button" className="verify-upload-btn" onClick={() => selfieCameraRef.current?.click()}>Take Selfie</button>
                                  <button type="button" className="verify-upload-btn" onClick={() => selfieGalleryRef.current?.click()}>Upload from Gallery</button>
                                </div>
                                <input
                                  ref={selfieCameraRef}
                                  type="file"
                                  accept="image/*"
                                  capture="user"
                                  className="hidden"
                                  onChange={(e) => handleIdentityImageUpload(e, 'selfieUrl', 'selfieName')}
                                />
                                <input
                                  ref={selfieGalleryRef}
                                  type="file"
                                  accept="image/*"
                                  className="hidden"
                                  onChange={(e) => handleIdentityImageUpload(e, 'selfieUrl', 'selfieName')}
                                />
                                <p className="verify-upload-name">{identityUploads.selfieName || identityFieldConfig.selfieUrl.placeholder}</p>
                                {form.selfieUrl && <img src={form.selfieUrl} alt="Selfie preview" className="verify-preview" />}
                              </div>
                              <p className="verify-helper">{identityFieldConfig.selfieUrl.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.selfieUrl.trustCue}</p>
                              {identityTouched.selfieUrl && getIdentityFieldError('selfieUrl', form.selfieUrl) && <p className="verify-error">{getIdentityFieldError('selfieUrl', form.selfieUrl)}</p>}
                            </div>

                            <div>
                              <label className="verify-label">{identityFieldConfig.faceMatchScore.label}</label>
                              <input type="number" value={form.faceMatchScore} readOnly className={`verify-input ${Number(form.faceMatchScore || 0) > 0 && Number(form.faceMatchScore || 0) < 60 ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.faceMatchScore.placeholder} />
                              <p className="verify-helper">{identityFieldConfig.faceMatchScore.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.faceMatchScore.trustCue}</p>
                              {Number(form.faceMatchScore || 0) > 0 && Number(form.faceMatchScore || 0) < 60 && <p className="verify-error">Face match is below confidence threshold. Use clearer images and retry.</p>}
                              {Number(form.faceMatchScore || 0) >= 60 && <p className="verify-success">Face match confidence looks good.</p>}
                            </div>
                            </div>
                          </div>
                        )}

                        {idVerificationReady && (
                          <div className="space-y-4">
                            <p className="text-[11px] uppercase tracking-[0.14em] font-black text-[#5B65DC]">C. Professional Footprint</p>
                            <div className="grid md:grid-cols-2 gap-4">
                            <div className="md:col-span-2">
                              <label className="verify-label">{identityFieldConfig.linkedinUrl.label}</label>
                              <input value={form.linkedinUrl} onChange={(e) => up('linkedinUrl', e.target.value)} className={`verify-input ${identityTouched.linkedinUrl && getIdentityFieldError('linkedinUrl', form.linkedinUrl) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.linkedinUrl.placeholder} />
                              <p className="verify-helper">{identityFieldConfig.linkedinUrl.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.linkedinUrl.trustCue}</p>
                              {linkedInStatus.state === 'checking' && <p className="verify-helper">{linkedInStatus.message}</p>}
                              {linkedInStatus.state === 'valid' && <p className="verify-success">{linkedInStatus.message}</p>}
                              {linkedInStatus.state === 'invalid' && <p className="verify-error">{linkedInStatus.message}</p>}
                              {identityTouched.linkedinUrl && getIdentityFieldError('linkedinUrl', form.linkedinUrl) && <p className="verify-error">{getIdentityFieldError('linkedinUrl', form.linkedinUrl)}</p>}
                            </div>

                            <div className="md:col-span-2">
                              <label className="verify-label">{identityFieldConfig.linkedinHeadline.label}</label>
                              <textarea value={form.linkedinHeadline} onChange={(e) => up('linkedinHeadline', e.target.value)} className={`verify-input resize-none min-h-[90px] ${identityTouched.linkedinHeadline && getIdentityFieldError('linkedinHeadline', form.linkedinHeadline) ? 'verify-input-error' : ''}`} placeholder={identityFieldConfig.linkedinHeadline.placeholder} />
                              <p className="verify-helper">{identityFieldConfig.linkedinHeadline.helper}</p>
                              <p className="verify-trust">{identityFieldConfig.linkedinHeadline.trustCue}</p>
                              {identityTouched.linkedinHeadline && getIdentityFieldError('linkedinHeadline', form.linkedinHeadline) && <p className="verify-error">{getIdentityFieldError('linkedinHeadline', form.linkedinHeadline)}</p>}
                            </div>
                            </div>
                          </div>
                        )}
                      </div>

                      <div className="rounded-2xl border border-[#E7ECFF] bg-[#FBFCFF] p-4 lg:sticky lg:top-24">
                        <p className="text-[11px] uppercase tracking-[0.14em] font-black text-[#5B65DC] inline-flex items-center gap-2"><Info size={14} /> Progress & Errors</p>

                        <div className="mt-4 flex items-center justify-center">
                          <div
                            className="verify-pie"
                            style={{
                              background: `conic-gradient(#5B65DC ${step1CompletionPercent * 3.6}deg, #E7ECFF 0deg)`
                            }}
                          >
                            <div className="verify-pie-inner">
                              <span className="verify-pie-value">{step1CompletionPercent}%</span>
                              <span className="verify-pie-label">Complete</span>
                            </div>
                          </div>
                        </div>

                        <p className="text-xs text-[#122056]/60 mt-4">Authenticity Score: <span className="font-bold text-[#122056]">{authenticityPreview}</span></p>

                        <div className="mt-3 space-y-2 max-h-[240px] overflow-auto pr-1">
                          {step1ErrorList.length === 0 ? (
                            <p className="text-sm text-emerald-700 inline-flex items-start gap-2"><CheckCircle size={14} className="mt-0.5" />All required fields look good.</p>
                          ) : (
                            step1ErrorList.map((error) => (
                              <p key={error} className="text-sm text-amber-700 flex items-start gap-2"><AlertTriangle size={14} className="mt-0.5" />{error}</p>
                            ))
                          )}
                        </div>
                      </div>
                    </div>
                  )}

                  {step === 1 && (
                    <div className="grid lg:grid-cols-[1.35fr_0.65fr] gap-6 items-start">
                      <div className="space-y-4">
                        <div className="execution-card">
                          <div className="execution-card-head">
                            <div>
                              <p className="execution-kicker">Product Footprint</p>
                              <p className="execution-status">{executionSections[0].complete ? 'Strong proof' : 'Needs stronger proof'} · +{executionSections[0].contribution} pts</p>
                            </div>
                            <span className="execution-badge-mini">Core 1</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <label className="verify-label">Startup Name</label>
                            <input value={form.startupName} onChange={(e) => up('startupName', e.target.value)} className="verify-input" placeholder="Startup name" />

                            <label className="verify-label">Build Stage</label>
                            <div className="flex flex-wrap gap-2">
                              {executionStageOptions.map((opt) => (
                                <button
                                  key={opt.value}
                                  type="button"
                                  className={`execution-chip ${form.prototypeStage === opt.value ? 'execution-chip-active' : ''}`}
                                  onClick={() => up('prototypeStage', opt.value)}
                                >
                                  {opt.label}
                                </button>
                              ))}
                            </div>

                            <div className="grid md:grid-cols-2 gap-3">
                              <input value={form.mvpLink} onChange={(e) => up('mvpLink', e.target.value)} className="verify-input" placeholder="MVP URL" />
                              <input value={form.demoLink} onChange={(e) => up('demoLink', e.target.value)} className="verify-input" placeholder="Demo video URL" />
                              <input value={form.githubUrl} onChange={(e) => up('githubUrl', e.target.value)} className="verify-input" placeholder="GitHub repository URL" />
                              <input value={form.websiteUrl} onChange={(e) => up('websiteUrl', e.target.value)} className="verify-input" placeholder="Website URL" />
                            </div>

                            <p className="text-xs text-[#122056]/58">Tip: Add at least 2 links to unlock a stronger execution score.</p>
                          </div>
                        </div>

                        <div className="execution-card">
                          <div className="execution-card-head">
                            <div>
                              <p className="execution-kicker">Narrative Clarity</p>
                              <p className="execution-status">{executionSections[1].complete ? 'Clear narrative' : 'Narrative needs depth'} · +{executionSections[1].contribution} pts</p>
                            </div>
                            <span className="execution-badge-mini">Core 2</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <label className="verify-label">Problem Statement</label>
                            <textarea
                              value={form.problemStatement}
                              onChange={(e) => up('problemStatement', e.target.value)}
                              className="verify-input resize-none min-h-[100px]"
                              placeholder="What painful user problem are you solving?"
                            />
                            <p className="text-xs text-[#122056]/55">Current depth: {(form.problemStatement || '').trim().length} characters</p>

                            <label className="verify-label">Solution Description</label>
                            <textarea
                              value={form.solutionDescription}
                              onChange={(e) => up('solutionDescription', e.target.value)}
                              className="verify-input resize-none min-h-[120px]"
                              placeholder="Explain your workflow, value delivery, and why your approach wins."
                            />
                            <p className="text-xs text-[#122056]/55">Current depth: {(form.solutionDescription || '').trim().length} characters</p>
                          </div>
                        </div>

                        <div className="execution-card">
                          <div className="execution-card-head">
                            <div>
                              <p className="execution-kicker">Visual Proof Vault</p>
                              <p className="execution-status">{executionSections[2].complete ? 'Evidence linked' : 'Add evidence links'} · +{executionSections[2].contribution} pts</p>
                            </div>
                            <span className="execution-badge-mini">Core 3</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <label className="verify-label">Screenshot URLs</label>
                            <input
                              value={form.screenshotLinks}
                              onChange={(e) => up('screenshotLinks', e.target.value)}
                              className="verify-input"
                              placeholder="https://.../screen1.png, https://.../screen2.png"
                            />
                            <p className="text-xs text-[#122056]/58">Use comma-separated links for onboarding, dashboard, and key outcomes.</p>
                          </div>
                        </div>
                      </div>

                      <div className="execution-panel lg:sticky lg:top-24">
                        <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC] inline-flex items-center gap-2"><Brain size={14} /> Live Execution Engine</p>
                        <p className="text-2xl font-black text-[#122056] mt-2">{executionLive.score}<span className="text-sm font-semibold text-[#122056]/45"> / 100</span></p>

                        <div className="execution-progress-track mt-3">
                          <div style={{ width: `${executionProgress}%` }} />
                        </div>
                        <p className="text-xs text-[#122056]/58 mt-2">Section completion: {executionProgress}%</p>

                        <div className="mt-3 space-y-2">
                          {executionLive.flags.length === 0 ? (
                            <p className="text-sm text-emerald-700 inline-flex items-start gap-2"><CheckCircle size={14} className="mt-0.5" />Execution signals look balanced and investor-friendly.</p>
                          ) : (
                            executionLive.flags.map((item) => (
                              <p key={item} className="text-sm text-amber-700 inline-flex items-start gap-2"><AlertTriangle size={14} className="mt-0.5" />{item}</p>
                            ))
                          )}
                        </div>

                        <div className="mt-4 pt-3 border-t border-[#E8ECFF] space-y-2">
                          <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC]">Evidence Checks</p>
                          <p className={`text-sm ${executionSections[0].complete ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Product Proof</p>
                          <p className={`text-sm ${executionSections[1].complete ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Narrative Clarity</p>
                          <p className={`text-sm ${executionSections[2].complete ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Visual Evidence</p>
                        </div>

                        <div className="mt-4 pt-3 border-t border-[#E8ECFF]">
                          <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC] inline-flex items-center gap-1"><Sparkles size={12} /> Next Best Action</p>
                          <p className="text-sm text-[#122056]/72 mt-1">{executionNextAction}</p>
                        </div>

                        {executionCriticalErrors.length > 0 && (
                          <div className="mt-4 pt-3 border-t border-[#E8ECFF] space-y-1">
                            <p className="text-[11px] uppercase tracking-[0.13em] font-black text-rose-600">Fix Before Continue</p>
                            {executionCriticalErrors.slice(0, 4).map((issue) => (
                              <p key={issue} className="text-sm text-rose-700">{issue}</p>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  {step === 2 && (
                    <div className="grid lg:grid-cols-[1.35fr_0.65fr] gap-6 items-start">
                      <div className="space-y-4">
                        <div className="readiness-card">
                          <div className="readiness-card-head">
                            <div>
                              <p className="readiness-kicker">Traction Signals</p>
                              <p className="readiness-status">{readinessSections[0].complete ? 'Completed' : 'Needs Work'} · +{readinessSections[0].contribution} pts</p>
                            </div>
                            <span className="readiness-badge-mini">Section 1</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <label className="verify-label">Total Users</label>
                            <div className="flex flex-wrap gap-2">
                              {userRangeOptions.map((opt) => (
                                <button
                                  key={opt.label}
                                  type="button"
                                  className={`readiness-chip ${Number(form.totalUsers || 0) === opt.value ? 'readiness-chip-active' : ''}`}
                                  onClick={() => up('totalUsers', opt.value)}
                                >
                                  {opt.label}
                                </button>
                              ))}
                            </div>
                            <input
                              type="number"
                              value={form.totalUsers}
                              onChange={(e) => up('totalUsers', e.target.value)}
                              className="verify-input"
                              placeholder="Or enter exact total users"
                            />

                            <label className="verify-label">Monthly Active Users</label>
                            <input type="number" value={form.monthlyActiveUsers} onChange={(e) => up('monthlyActiveUsers', e.target.value)} className="verify-input" placeholder="Enter MAU" />

                            <div className="readiness-range-head">
                              <label className="verify-label mb-0">Monthly Growth Rate</label>
                              <span className="readiness-range-value">{Number(form.growthRateMonthly || 0)}%</span>
                            </div>
                            <input
                              type="range"
                              min="0"
                              max="100"
                              step="1"
                              value={Number(form.growthRateMonthly || 0)}
                              onChange={(e) => up('growthRateMonthly', e.target.value)}
                              className="readiness-range"
                              style={{
                                background: `linear-gradient(90deg, #1E3A8A 0%, #2563EB ${Number(form.growthRateMonthly || 0)}%, #E7ECFF ${Number(form.growthRateMonthly || 0)}%, #E7ECFF 100%)`
                              }}
                            />
                            <div className="readiness-range-ticks">
                              <span>0%</span>
                              <span>25%</span>
                              <span>50%</span>
                              <span>75%</span>
                              <span>100%</span>
                            </div>
                            <div className="readiness-mini-graph">
                              <div style={{ width: `${Math.min(100, Number(form.growthRateMonthly || 0))}%` }} />
                            </div>
                          </div>
                        </div>

                        <div className="readiness-card">
                          <div className="readiness-card-head">
                            <div>
                              <p className="readiness-kicker">Business Model</p>
                              <p className="readiness-status">{readinessSections[1].complete ? 'Completed' : 'Needs Work'} · +{readinessSections[1].contribution} pts</p>
                            </div>
                            <span className="readiness-badge-mini">Section 2</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <label className="verify-label">Revenue State</label>
                            <div className="flex gap-2 flex-wrap">
                              <button type="button" className={`readiness-chip ${revenueMode === 'pre-revenue' ? 'readiness-chip-active' : ''}`} onClick={() => setRevenueMode('pre-revenue')}>Pre-revenue</button>
                              <button type="button" className={`readiness-chip ${revenueMode === 'revenue' ? 'readiness-chip-active' : ''}`} onClick={() => setRevenueMode('revenue')}>Generating revenue</button>
                            </div>
                            {revenueMode === 'revenue' && (
                              <input type="number" value={form.monthlyRevenue} onChange={(e) => up('monthlyRevenue', e.target.value)} className="verify-input" placeholder="Monthly revenue (USD)" />
                            )}

                            <label className="verify-label">Funding Ask</label>
                            <div className="flex flex-wrap gap-2 mb-2">
                              {askSuggestions.map((ask) => (
                                <button key={ask} type="button" className={`readiness-chip ${Number(form.askAmountUsd || 0) === ask ? 'readiness-chip-active' : ''}`} onClick={() => up('askAmountUsd', ask)}>
                                  ${ask.toLocaleString()}
                                </button>
                              ))}
                            </div>
                            <input type="number" value={form.askAmountUsd} onChange={(e) => up('askAmountUsd', e.target.value)} className="verify-input" placeholder="Custom ask amount (USD)" />

                            <label className="verify-label">Pitch Deck Upload</label>
                            <div
                              className={`readiness-dropzone ${isDeckDragOver ? 'readiness-dropzone-over' : ''}`}
                              onDragOver={(e) => {
                                e.preventDefault()
                                setIsDeckDragOver(true)
                              }}
                              onDragLeave={() => setIsDeckDragOver(false)}
                              onDrop={(e) => {
                                e.preventDefault()
                                setIsDeckDragOver(false)
                                const file = e.dataTransfer.files?.[0]
                                handleDeckFile(file)
                              }}
                            >
                              <p className="text-sm text-[#122056]/70">Drag & drop your deck (.pdf, .ppt, .pptx) or</p>
                              <button type="button" className="verify-upload-btn mt-2" onClick={() => deckUploadRef.current?.click()}>Choose file</button>
                              <input
                                ref={deckUploadRef}
                                type="file"
                                accept=".pdf,.ppt,.pptx,.key,.odp"
                                className="hidden"
                                onChange={(e) => handleDeckFile(e.target.files?.[0])}
                              />
                              <p className={`text-xs mt-2 ${deckUpload.status === 'uploaded' ? 'text-emerald-700' : deckUpload.status === 'error' ? 'text-rose-600' : 'text-[#122056]/50'}`}>
                                {deckUpload.status === 'uploaded' ? `Uploaded: ${deckUpload.fileName}` : deckUpload.status === 'error' ? deckUpload.fileName : 'No deck uploaded yet'}
                              </p>
                            </div>

                            <label className="verify-label">Business Description (Text / Voice Assist)</label>
                            <div className="flex gap-2 flex-wrap mb-2">
                              <button type="button" className="readiness-chip" onClick={startVoiceCapture}><Mic size={13} /> Start voice input</button>
                              <span className="text-xs text-[#122056]/55">Status: {voiceStatus}</span>
                            </div>
                            {voiceNote && <p className="text-xs text-[#122056]/60">Captured note: {voiceNote}</p>}
                            <textarea value={form.businessModel} onChange={(e) => up('businessModel', e.target.value)} className="verify-input resize-none min-h-[96px]" placeholder="How do you make money? Include pricing, margins, and sales motion." />
                            <div className="readiness-ai-note">
                              <p className="text-[11px] uppercase tracking-[0.12em] font-black text-[#5B65DC] inline-flex items-center gap-1"><Sparkles size={12} /> AI Summary</p>
                              <p className="text-sm text-[#122056]/70 mt-1">{(form.businessModel || '').trim().length > 20 ? `${form.businessModel.trim().split('.').slice(0, 2).join('.').trim()}.` : 'Add business details and we will auto-summarize your model here.'}</p>
                            </div>
                          </div>
                        </div>

                        <div className="readiness-card">
                          <div className="readiness-card-head">
                            <div>
                              <p className="readiness-kicker">Market Understanding</p>
                              <p className="readiness-status">{readinessSections[2].complete ? 'Completed' : 'Needs Work'} · +{readinessSections[2].contribution} pts</p>
                            </div>
                            <span className="readiness-badge-mini">Section 3</span>
                          </div>

                          <div className="space-y-3 mt-3">
                            <textarea value={form.targetMarket} onChange={(e) => up('targetMarket', e.target.value)} className="verify-input resize-none min-h-[92px]" placeholder="Who is your ideal customer? Which segment is growing fastest?" />
                            <textarea value={form.competitors} onChange={(e) => up('competitors', e.target.value)} className="verify-input resize-none min-h-[92px]" placeholder="Who are your competitors and what is your strongest edge?" />
                          </div>
                        </div>
                      </div>

                      <div className="readiness-panel lg:sticky lg:top-24">
                        <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC] inline-flex items-center gap-2"><Brain size={14} /> Live Evaluation Engine</p>
                        <p className="text-2xl font-black text-[#122056] mt-2">{readinessLive.score}<span className="text-sm font-semibold text-[#122056]/45"> / 100</span></p>

                        <div className="mt-3 space-y-2">
                          {readinessAiFeedback.positives.map((item) => <p key={item} className="text-sm text-emerald-700">{item}</p>)}
                          {readinessAiFeedback.warnings.map((item) => <p key={item} className="text-sm text-amber-700">{item}</p>)}
                          {readinessAiFeedback.redFlags.map((item) => <p key={item} className="text-sm text-rose-700">{item}</p>)}
                        </div>

                        <div className="mt-4 pt-3 border-t border-[#E8ECFF] space-y-2">
                          <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC]">Unlocked Badges</p>
                          <p className={`text-sm ${readinessBadges.builder ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Builder</p>
                          <p className={`text-sm ${readinessBadges.growingStartup ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Growing Startup</p>
                          <p className={`text-sm ${readinessBadges.investorReady ? 'text-emerald-700' : 'text-[#122056]/45'}`}>Investor Ready</p>
                        </div>

                        <div className="mt-4 pt-3 border-t border-[#E8ECFF]">
                          <p className="text-[11px] uppercase tracking-[0.13em] font-black text-[#5B65DC] inline-flex items-center gap-1"><DollarSign size={12} /> Next Best Action</p>
                          <p className="text-sm text-[#122056]/72 mt-1">{readinessNextAction}</p>
                        </div>

                        {readinessCriticalErrors.length > 0 && (
                          <div className="mt-4 pt-3 border-t border-[#E8ECFF] space-y-1">
                            <p className="text-[11px] uppercase tracking-[0.13em] font-black text-rose-600">Critical Fixes</p>
                            {readinessCriticalErrors.slice(0, 4).map((issue) => (
                              <p key={issue} className="text-sm text-rose-700">{issue}</p>
                            ))}
                          </div>
                        )}
                      </div>
                    </div>
                  )}

                  <div className="mt-8 pt-6 border-t border-[#EEF0FD] flex items-center justify-between">
                    <button onClick={() => setStep((prev) => Math.max(prev - 1, 0))} className={`px-4 py-2 rounded-xl border text-sm font-semibold inline-flex items-center gap-2 ${step === 0 ? 'opacity-40 pointer-events-none border-slate-200 text-slate-400' : 'border-[#D8E1FF] text-[#122056] hover:bg-[#F7F9FF]'}`}>
                      <ChevronLeft size={14} /> Back
                    </button>

                    {step < 2 ? (
                      <button
                        onClick={handleNext}
                        className="px-5 py-2.5 rounded-xl text-sm font-semibold inline-flex items-center gap-2 bg-[#122056] text-white hover:opacity-95"
                      >
                        Save & continue <ChevronRight size={14} />
                      </button>
                    ) : (
                      <button
                        onClick={handleSubmit}
                        disabled={step === 2 && readinessCriticalErrors.length > 0}
                        className={`px-5 py-2.5 rounded-xl text-sm font-semibold inline-flex items-center gap-2 ${step === 2 && readinessCriticalErrors.length > 0 ? 'bg-emerald-300 text-white/90 cursor-not-allowed' : 'bg-emerald-600 text-white hover:opacity-95'}`}
                      >
                        Submit Verification <CheckCircle size={14} />
                      </button>
                    )}
                  </div>
                </div>
              </motion.div>
            ) : (
              <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl mx-auto">
                <div className="bg-white rounded-[2rem] border border-[#E8EDFD] p-7 shadow-[0_20px_48px_-16px_rgba(18,32,86,0.12)]">
                  <div className="w-12 h-12 rounded-2xl bg-emerald-100 text-emerald-700 flex items-center justify-center mb-4">
                    <Shield size={22} />
                  </div>
                  <p className="text-[11px] uppercase tracking-[0.15em] font-black text-[#5B65DC]">Verification Complete</p>
                  <h2 className="text-3xl font-serif text-[#122056] mt-1">Your profile has been verified</h2>
                  <p className="text-sm text-[#122056]/65 mt-2">This is a one-time verification. You can now continue to your founder dashboard.</p>

                  <div className="mt-7 flex items-center gap-3">
                    <button onClick={() => navigate('/dashboard/founder')} className="px-4 py-2 rounded-xl bg-[#122056] text-white text-sm font-semibold">Go to Founder Dashboard</button>
                  </div>
                </div>
              </motion.div>
            )}
          </div>
        </section>
      </main>
      <Footer />

      <style dangerouslySetInnerHTML={{ __html: `
        .verify-input {
          width: 100%;
          padding: 0.85rem 1rem;
          border-radius: 0.9rem;
          border: 1px solid #E7ECFF;
          background: #F8FAFF;
          color: #122056;
          font-size: 0.875rem;
          font-weight: 600;
          transition: all 0.3s ease;
        }
        .verify-input:focus {
          outline: none;
          border-color: #5f6cdc;
          background: white;
          box-shadow: 0 0 0 4px rgba(95, 108, 220, 0.08);
        }
        .verify-input::placeholder {
          color: rgba(18, 32, 86, 0.2);
          font-weight: 500;
        }
        .verify-input-error {
          border-color: #fca5a5;
          background: #fff7f7;
          box-shadow: 0 0 0 3px rgba(252, 165, 165, 0.18);
        }
        .verify-label {
          display: block;
          margin-bottom: 0.45rem;
          font-size: 0.8rem;
          font-weight: 800;
          letter-spacing: 0.01em;
          color: #122056;
        }
        .verify-helper {
          margin-top: 0.35rem;
          font-size: 0.76rem;
          color: rgba(18, 32, 86, 0.62);
        }
        .verify-trust {
          margin-top: 0.15rem;
          font-size: 0.72rem;
          color: #2d5b9a;
          font-weight: 600;
        }
        .verify-error {
          margin-top: 0.35rem;
          font-size: 0.78rem;
          color: #b42318;
          font-weight: 600;
        }
        .verify-success {
          margin-top: 0.35rem;
          font-size: 0.78rem;
          color: #067647;
          font-weight: 600;
        }
        .verify-upload-box {
          width: 100%;
          padding: 0.85rem 1rem;
          border-radius: 0.9rem;
          border: 1px solid #E7ECFF;
          background: #F8FAFF;
        }
        .verify-upload-btn {
          border: 1px solid #cfd9ff;
          background: white;
          color: #122056;
          font-size: 0.75rem;
          font-weight: 700;
          border-radius: 0.6rem;
          padding: 0.4rem 0.65rem;
        }
        .verify-upload-name {
          margin-top: 0.55rem;
          font-size: 0.78rem;
          color: rgba(18, 32, 86, 0.62);
          font-weight: 600;
        }
        .verify-preview {
          margin-top: 0.6rem;
          width: 100%;
          max-height: 140px;
          border-radius: 0.7rem;
          object-fit: cover;
          border: 1px solid #dfe7ff;
        }
        .verify-pie {
          width: 132px;
          height: 132px;
          border-radius: 999px;
          display: flex;
          align-items: center;
          justify-content: center;
        }
        .verify-pie-inner {
          width: 92px;
          height: 92px;
          border-radius: 999px;
          background: white;
          border: 1px solid #e8edff;
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;
          line-height: 1.1;
        }
        .verify-pie-value {
          font-size: 1.2rem;
          font-weight: 800;
          color: #122056;
        }
        .verify-pie-label {
          font-size: 0.68rem;
          letter-spacing: 0.08em;
          text-transform: uppercase;
          color: #5b65dc;
          font-weight: 700;
          margin-top: 0.15rem;
        }
        .readiness-card {
          border: 1px solid #e7ecff;
          border-radius: 1rem;
          background: #fbfcff;
          padding: 1rem;
        }
        .execution-card {
          border: 1px solid #e7ecff;
          border-radius: 1rem;
          background: #fbfcff;
          padding: 1rem;
        }
        .execution-card-head {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 0.75rem;
        }
        .execution-kicker {
          font-size: 0.72rem;
          letter-spacing: 0.13em;
          text-transform: uppercase;
          color: #5b65dc;
          font-weight: 800;
        }
        .execution-status {
          margin-top: 0.25rem;
          font-size: 0.78rem;
          color: rgba(18, 32, 86, 0.58);
          font-weight: 600;
        }
        .execution-badge-mini {
          font-size: 0.68rem;
          font-weight: 800;
          color: #2d3fb8;
          background: #eef2ff;
          border: 1px solid #dde4ff;
          border-radius: 999px;
          padding: 0.25rem 0.55rem;
          white-space: nowrap;
        }
        .execution-chip {
          border: 1px solid #d5defe;
          color: #122056;
          background: white;
          border-radius: 999px;
          padding: 0.42rem 0.75rem;
          font-size: 0.75rem;
          font-weight: 700;
        }
        .execution-chip-active {
          background: #122056;
          color: white;
          border-color: #122056;
        }
        .execution-panel {
          border: 1px solid #e7ecff;
          border-radius: 1rem;
          background: #ffffff;
          padding: 1rem;
        }
        .execution-progress-track {
          height: 8px;
          border-radius: 999px;
          background: #e9edff;
          overflow: hidden;
        }
        .execution-progress-track > div {
          height: 100%;
          border-radius: 999px;
          background: linear-gradient(90deg, #1d4ed8, #0ea5e9);
          transition: width 0.25s ease;
        }
        .readiness-card-head {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 0.75rem;
        }
        .readiness-kicker {
          font-size: 0.72rem;
          letter-spacing: 0.13em;
          text-transform: uppercase;
          color: #5b65dc;
          font-weight: 800;
        }
        .readiness-status {
          margin-top: 0.25rem;
          font-size: 0.78rem;
          color: rgba(18, 32, 86, 0.58);
          font-weight: 600;
        }
        .readiness-badge-mini {
          font-size: 0.68rem;
          font-weight: 800;
          color: #2d3fb8;
          background: #eef2ff;
          border: 1px solid #dde4ff;
          border-radius: 999px;
          padding: 0.25rem 0.55rem;
          white-space: nowrap;
        }
        .readiness-chip {
          border: 1px solid #d5defe;
          color: #122056;
          background: white;
          border-radius: 999px;
          padding: 0.42rem 0.75rem;
          font-size: 0.75rem;
          font-weight: 700;
          display: inline-flex;
          align-items: center;
          gap: 0.3rem;
        }
        .readiness-chip-active {
          background: #122056;
          color: white;
          border-color: #122056;
        }
        .readiness-mini-graph {
          height: 8px;
          border-radius: 999px;
          background: #e9edff;
          overflow: hidden;
        }
        .readiness-mini-graph > div {
          height: 100%;
          border-radius: 999px;
          background: linear-gradient(90deg, #5b65dc, #0ea5e9);
          transition: width 0.25s ease;
        }
        .readiness-range-head {
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 0.4rem;
        }
        .readiness-range-value {
          font-size: 0.82rem;
          font-weight: 800;
          color: #1e3a8a;
          background: #e9efff;
          border: 1px solid #d8e4ff;
          padding: 0.2rem 0.5rem;
          border-radius: 999px;
        }
        .readiness-range {
          -webkit-appearance: none;
          appearance: none;
          width: 100%;
          height: 10px;
          border-radius: 999px;
          outline: none;
        }
        .readiness-range::-webkit-slider-thumb {
          -webkit-appearance: none;
          appearance: none;
          width: 18px;
          height: 18px;
          border-radius: 50%;
          background: white;
          border: 2px solid #1d4ed8;
          box-shadow: 0 4px 12px rgba(29, 78, 216, 0.35);
          cursor: pointer;
        }
        .readiness-range::-moz-range-thumb {
          width: 18px;
          height: 18px;
          border-radius: 50%;
          background: white;
          border: 2px solid #1d4ed8;
          box-shadow: 0 4px 12px rgba(29, 78, 216, 0.35);
          cursor: pointer;
        }
        .readiness-range-ticks {
          margin-top: 0.35rem;
          display: flex;
          justify-content: space-between;
          font-size: 0.68rem;
          color: rgba(18, 32, 86, 0.52);
          font-weight: 700;
        }
        .readiness-dropzone {
          border: 1.5px dashed #cfd8ff;
          border-radius: 0.95rem;
          background: white;
          padding: 1rem;
          text-align: center;
        }
        .readiness-dropzone-over {
          background: #f4f7ff;
          border-color: #5b65dc;
        }
        .readiness-ai-note {
          border: 1px solid #e6ebff;
          background: #f9fbff;
          border-radius: 0.75rem;
          padding: 0.7rem;
        }
        .readiness-panel {
          border: 1px solid #e7ecff;
          border-radius: 1rem;
          background: #ffffff;
          padding: 1rem;
        }
        .verify-checkbox {
          display: flex;
          align-items: center;
          gap: 0.6rem;
          font-size: 0.85rem;
          color: rgba(18, 32, 86, 0.75);
          font-weight: 600;
        }
        .verify-checkbox input {
          accent-color: #122056;
        }
      `}} />
    </>
  )
}

export default VerifyPage
